### ISSUE TITLE
Is there a way to suppress some requests from Public view?

### ISSUE THREAD

**Issue by n7k1** [randybondsjr/recordtrac-cakephp#17]
I'd like the ability to suppress some records from public view.  Before I code in the functionality, I thought I'd check to see if the functionality already exists and I'm not seeing how to enable it.  I see there is a function 'is_public_record' in RequestsController.  

Thanks.

**Comment by randybondsjr** [comment]
There isn't a built in function, we actually ended up just hiding all requests from public view on our current installation. 

The is_public_record function really should be called something else, it checks and sees if the request has a word in it that may indicate the request should be taken care of by another agency. (Like marriage licenses, those are handled by the county rather than the city)

**Comment by randybondsjr** [comment]
You can check out https://github.com/CityofYakima/recordtrac-cakephp/tree/coy-change to see the one completely hidden from public
